task: prob_occ
global_seed: 0
vis: false
vis_graph: false
print_options: s,b,ab,r,a,o,sp,bp,abp,rp
max_steps: 10
batch_size: 100
num_skeletons: 10
flat_sample: true
flat_width: 3
pwa: 0.2
pwk: 3.0
envelope_threshold: 1
num_samples: 500
gamma: 0.98
planner: tampura_policy
learning_strategy: bayes_optimistic
decision_strategy: prob
symk_selection: top_k
symk_direction: fw
symk_simple: true
from_scratch: false
