task: tool_use
global_seed: 0
vis: false
vis_graph: false
print_options: s,b,ab,r,a,o,sp,bp,abp,rp
max_steps: 20
batch_size: 20
num_skeletons: 10
flat_sample: false
flat_width: 10
pwa: 0.5
pwk: 3.0
envelope_threshold: 1
num_samples: 300
gamma: 0.98
planner: tampura_policy
learning_strategy: bayes_optimistic
decision_strategy: prob
symk_selection: unordered
symk_direction: bd
symk_simple: true
from_scratch: false
