task: toy_discrete
global_seed: 0
vis: false
vis_graph: false
print_options: s,b,ab,r,a,o,sp,bp,abp,rp
max_steps: 5
batch_size: 100
num_skeletons: 1
flat_sample: true
flat_width: 10
action_pwa: 0.2
action_pwk: 3.0
output_pwa: 0.0
output_pwk: 1.0
envelope_threshold: 1
num_samples: 500
gamma: 0.98
planner: tampura_policy
learning_strategy: bayes_optimistic
decision_strategy: prob
symk_selection: unordered
symk_direction: bd
symk_simple: true
from_scratch: false
